In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry.polygon import Polygon
from h3 import h3 
from shapely.geometry import shape
from shapely.geometry import Point

In [2]:
df=pd.read_csv('taxi_complete.csv', parse_dates=['Trip Start Timestamp','Trip End Timestamp'])
df=df.drop('Unnamed: 0',axis=1)

In [3]:
df

,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Fare,Tips,Tolls,Extras,Payment Type,Company,...,Dropoff Census Tract,Pickup Census Tract,date,weekday,avg_temp,precip,hour,day,month,h3_hex_id_start
0,2017-05-12 21:00:00,2017-05-12 21:15:00,865.0,4.6,15.00,2.55,0.0,2.0,Credit Card,American United,...,17031070300,17031320100,2017-05-12 00:00:00,4,21.1,0.0,21,12,5,8a2664c1e2effff
1,2017-04-27 11:30:00,2017-04-27 11:30:00,20.0,0.0,3.25,0.65,0.0,1.0,Credit Card,American United,...,17031210601,17031210601,2017-04-27 00:00:00,3,14.4,1.0,11,27,4,8a2664ca0aa7fff
2,2017-06-29 01:00:00,2017-06-29 01:15:00,1560.0,17.1,33.65,0.00,0.0,2.0,Cash,Choice Taxi Association,...,17031081000,17031980000,2017-06-29 00:00:00,3,25.6,0.0,1,29,6,8a275934332ffff
3,2017-04-27 21:00:00,2017-04-27 21:30:00,2082.0,18.2,45.75,7.46,0.0,4.0,Credit Card,American United,...,17031062200,17031560800,2017-04-27 00:00:00,3,7.8,0.0,21,27,4,8a2664520ad7fff
4,2017-05-03 14:15:00,2017-05-03 14:15:00,474.0,0.9,6.25,1.00,0.0,0.0,Credit Card,American United,...,17031081401,17031320100,2017-05-03 00:00:00,2,9.4,0.0,14,3,5,8a2664c1e2effff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5160231,2017-10-08 16:30:00,2017-10-08 17:45:00,4260.0,28.5,72.25,0.00,0.0,0.0,Dispute,Choice Taxi Association,...,17031980100,17031839000,2017-10-08 00:00:00,6,20.6,0.0,16,8,10,8a2664c1a04ffff
5160232,2017-10-22 18:00:00,2017-10-22 18:15:00,540.0,0.0,7.25,1.65,0.0,1.0,Credit Card,Blue Ribbon Taxi Association Inc.,...,17031833000,17031320100,2017-10-22 00:00:00,6,20.0,0.0,18,22,10,8a2664c1e2effff
5160233,2017-10-23 11:15:00,2017-10-23 11:15:00,360.0,0.0,6.00,3.00,0.0,0.0,Credit Card,Blue Ribbon Taxi Association Inc.,...,17031062200,17031071100,2017-10-23 00:00:00,0,10.6,1.0,11,23,10,8a2664c13d27fff
5160234,2017-10-07 13:45:00,2017-10-07 14:00:00,900.0,3.1,12.25,2.65,0.0,1.0,Credit Card,Star North Management LLC,...,17031081800,17031081500,2017-10-07 00:00:00,5,20.0,0.0,13,7,10,8a2664c1e0effff
5160235,2017-10-23 22:30:00,2017-10-23 22:45:00,900.0,3.9,13.75,2.00,0.0,0.0,Credit Card,Taxi Affiliation Services,...,17031242200,17031320400,2017-10-23 00:00:00,0,11.7,0.0,22,23,10,8a2664c1a847fff

In [4]:
df.count()

Trip Start Timestamp          5160236
Trip End Timestamp            5160236
Trip Seconds                  5160236
Trip Miles                    5160236
Fare                          5160236
Tips                          5160236
Tolls                         5160236
Extras                        5160236
Payment Type                  5160236
Company                       5160236
Pickup Centroid Latitude      5160236
Pickup Centroid Longitude     5160236
Dropoff Centroid Latitude     5160236
Dropoff Centroid Longitude    5160236
new_TaxiID                    5160236
Trips Total                   5160236
dur_min                       5160236
Dropoff Community Area        5160236
Pickup Community Area         5160236
Dropoff Census Tract          5160236
Pickup Census Tract           5160236
date                          5160236
weekday                       5160236
avg_temp                      5160236
precip                        5160236
hour                          5160236
day                           5160236
month                         5160236
h3_hex_id_start               5160236
dtype: int64